### ISSUE TITLE
Enhance filtering by allowing matches on metadata fields

### ISSUE THREAD

**Issue by mhmood-sf** [zk-org/zk#446] opened 2024-08-17 09:03 UTC
Right now you can filter notes by matching on the title and body, but AFAIK there is no way to filter by querying a note's metadata fields. For example, all my task notes have a status field in the metadata and it would be really convenient to be able to filter notes with a status of "incomplete"/"complete"/etc.

**Comment by tjex** [comment] 2024-08-17 15:37
duplicate of #1 .
I agree, would be nice.

**Closed by tjex** 2024-08-17 15:37 UTC
